spring:
  config:
    activate:
      on-profile: develop

  datasource:
    url: jdbc:postgresql://localhost:5432/social_media
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    liquibase:
      change-log: classpath:db/db.changelog-master.xml
      enabled: true
      drop-first: false
      contexts: develop
      parameters:
        env: development